# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=30)),
                ('competition', models.CharField(max_length=50)),
                ('teams', models.CharField(max_length=200)),
                ('participants', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('video_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('videocloud_id', models.BigIntegerField(unique=True)),
                ('wp_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('published', models.DateTimeField()),
                ('aired', models.DateTimeField()),
                ('url', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
